/*
 *	Name: Graphics
 *	Author: Pawel Mrochen
 */

#pragma once

#include "Rasterization/ComparisonFunction.hpp"
#include "Rasterization/BlendFunction.hpp"
#include "Rasterization/BlendEquation.hpp"
#include "Shading/TextureWrapMode.hpp"
#include "Shading/TextureFilter.hpp"
#include "Rasterization/DepthStencilFormat.hpp"
#include "Rasterization/MultisampleMode.hpp"
#include "Geometry/PrimitiveType.hpp"
#include "SceneGraph/Projection.hpp"
#include "Rasterization/ClipOrigin.hpp"
#include "Rasterization/NdcDepthRange.hpp"
#include "Rasterization/FrontFace.hpp"
#include "Rasterization/CullFaceMode.hpp"
#include "Rasterization/PolygonFillMode.hpp"
#include "Rasterization/DepthMask.hpp"
#include "Rasterization/AttributeMask.hpp"
#include "Rasterization/StencilOperation.hpp"
#include "Rasterization/RasterizerFlags.hpp"
#include "HardwareInterface/ResourceTypes.hpp"
#include "HardwareInterface/ResourceStorageFlags.hpp"
#include "Rasterization/FramebufferAccessMode.hpp"
#include "Geometry/VertexDataType.hpp"
#include "Geometry/VertexAttributeIndex.hpp"
#include "Geometry/VertexAttributeTypes.hpp"
#include "HardwareInterface/VertexStorageFlags.hpp"
#include "Geometry/Sidedness.hpp"
#include "Geometry/GeometryType.hpp"
#include "SceneGraph/LightTypes.hpp"
#include "SceneGraph/AppearanceFlags.hpp"
#include "Rasterization/ColorFormat.hpp"
#include "Shading/SamplerState.hpp"
#include "Rasterization/RasterizerState.hpp"
#include "Rasterization/ClearOptions.hpp"
#include "Rasterization/FramebufferAttributes.hpp"
#include "Rasterization/FramebufferOptions.hpp"
#include "Geometry/VertexAttributeInfo.hpp"
#include "Geometry/VertexLayout.hpp"
#include "Geometry/PrimitiveTopology.hpp"
#include "Rasterization/Viewport.hpp"
#include "SceneGraph/ViewVolume.hpp"
#include "SceneGraph/AppearanceOptions.hpp"
//#include "Geometry/Mesh.hpp"
//#include "Shading/Material.hpp"
//#include "Animation/FCurve.hpp"
//#include "SceneGraph/Locator.hpp"
