/*
 *	Name: Mathematics
 *	Author: Pawel Mrochen
 */

#pragma once

#include "Constants.hpp"
#include "Axis.hpp"
#include "EulerOrder.hpp"
#include "Vector2.hpp"
#include "Vector3.hpp"
#include "Vector4.hpp"
#include "IntVector2.hpp"
#include "IntVector3.hpp"
#include "IntVector4.hpp"
#include "Matrix2.hpp"
#include "Matrix3.hpp"
#include "AffineTransform.hpp"
#include "Matrix4.hpp"
#include "Quaternion.hpp"
#include "YawPitchRoll.hpp"
#include "Euler.hpp"
#include "Interval.hpp"
#include "AxisAlignedRectangle.hpp"
#include "Circle2.hpp"
#include "Line2.hpp"
#include "Ray2.hpp"
#include "Segment2.hpp"
#include "Line3.hpp"
#include "Ray3.hpp"
#include "Segment3.hpp"
#include "Triangle3.hpp"
#include "Quadrilateral3.hpp"
#include "Tetrahedron.hpp"
#include "HalfSpace.hpp"
#include "Plane.hpp"
#include "AxisAlignedBox.hpp"
#include "OrientedBox.hpp"
#include "Sphere.hpp"
#include "Ellipsoid.hpp"
#include "Cylinder.hpp"
#include "Capsule.hpp"
#include "Cone.hpp"
#include "SymmetricFrustum.hpp"
//#include "SkewedFrustum.hpp"
#include "Torus.hpp"
//#include "ConvexDecompositionOptions.hpp"
#include "Polyhedron.hpp"
#include "ConvexPolyhedron.hpp"
#include "TetrahedralMesh.hpp"
